sudo: required
language: ruby
os: linux
rvm:
  - 2.6.3
before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -q
  - sudo apt-get install ffmpeg -y
  - gem update --system
  - gem update bundler
install:
  - bundle install
script:
  - bundle exec rspec
