lang: ruby, python
rvm:
  - 2.5
  - 2.6
python:
  - 3.6
before_install:
  - travis_retry gem update --system || travis_retry gem update --system 2.7.8
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
install:
  - pip install --upgrade pip
  - pip install imagehash
script:
  - bundle exec rspec
branches:
  only:
    - master